<style scoped>
.full {
  height: 100%;
}
</style>

<template>
  <VuePerfectScrollbar class="full">
    * TODO articles eg have a blog made with Strapi
    <br>
* have a shop made with the same and stripe? or some other ecommerce API
    <template
      v-if="currentUser"
    >
      Logged in as
      <span class="card-text">{{currentUser.username}}</span>
      E-Mail:
      <span class="card-text">{{currentUser.email}}</span>
    </template>

    <b-button @click="createArticle">create</b-button>

    <b-card-group columns>
      <b-card
        v-for="(item,i, index) in articles"
        :title="item.title"
        :img-src="item.background"
        img-alt="Img"
      >
        <p class="card-text">{{item.content.substring(0,20)}}</p>
        <b-button @click="deleteArticle(item)">X</b-button>
      </b-card>
    </b-card-group>
  </VuePerfectScrollbar>
</template>
<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";

import VuePerfectScrollbar from "vue-perfect-scrollbar";

//--------------------------------------------------------------
// below code should be generated by the model => ts converter for each strapi instance (1 for starters)

import { IArticle } from "../../../../@strapi-types-project";
import { IUser } from "../../../../@strapi-types-core";

import { ServerConfig } from "../../../../@strapi-sdk-typescript/config";
const { strapiInstance, models } = new ServerConfig("http://localhost:1337");

//--------------------------------------------------------------

@Component({
  components: { VuePerfectScrollbar }
})
export default class MainNavigation extends Vue {
  articles: IArticle[] = [];
  users: IUser[] = [];
  currentUser: IUser = null;
  cardClicked(route) {
    this.$router.push(route);
  }

  async login() {
    const res = await strapiInstance.login("frank", "ztronkpassword");
    console.log("login", res);
    return res;
  }

  async mounted() {
    const login = await this.login();
    this.currentUser = login.user as IUser;

    const articles = (this.articles = await models.articles.all());
  }

  async createArticle() {
    const article = {
      title: "123",
      content: "test-123",
      background: "https://i.imgur.com/emSvYMy.gif" // http://cdn2.hubspot.net/hub/53/file-2478064512-gif/Agency_Post/Blog_Images/6714158709_86a86c4dfe_o.gif?t=1472028659685&width=650
    } as IArticle;

    const articleWithID = await models.articles.create(article);

    this.articles.unshift(articleWithID);
  }

  async deleteArticle(article) {
    await models.articles.delete(article.id);

    var index = this.articles.indexOf(article);
    if (index > -1) {
      this.articles.splice(index, 1);
    }
  }
}
</script>